import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanitFont = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Worker Ant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanitFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
